### ISSUE TITLE
Not Working with Common.Logging 3 and NHibernate 4

### ISSUE THREAD

**Issue by marcelmunarolo** [mgernand/NHibernate.Logging#4]
Dear Colleagues,

May I kindly ask you to compile a new version of this package, using the latest version of Common.Logging and NHibernate libraries in the net 45 framework?

When I try use this configuration, i receive the following error:
Method not found: 'Common.Logging.ILog Common.Logging.LogManager.GetLogger(System.Type)'.

Thank you very much!

**Comment by mgernand** [comment]
Hi,
I'll do it in the next few day. Thank you for being patient. ;-)

Am 27.05.2015 um 16:30 schrieb marcelmunarolo:

**Comment by mgernand** [comment]
The latest version 4.0.3 of NHibernate.Logging now supports Common.Logging 3 and NHibernate 4. It is now build for.NET 4.5.

**Comment by marcelmunarolo** [comment]
Thank you very much Matthias, it is really helpful!
Cheers!
